baseURL = "https://simplelogin.io/"
languageCode = "en-us"
title = "SimpleLogin | Protect your online identity with Email Alias"
enableRobotsTXT = true
canonifyURLs = true

# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"