---
#baseURL = "https://simplelogin.io/"
languageCode: "en-us"
title: "SimpleLogin | Open-source email alias solution"
enableRobotsTXT: true
canonifyURLs: true
disableKinds:
  - taxonomy
  - taxonomyTerm


# and if you think your md file names or locations might change:
permalinks:
    post: "/blog/:title/"

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 3


languages:
  en:
    weight: 1

  fr:
    title: "SimpleLogin | Protéger votre vie privée avec les alias mail"
    weight: 2
