baseURL = "https://simplelogin.io/"
languageCode = "en-us"
title = "SimpleLogin | Open source solution to protect your email address"
enableRobotsTXT = true
canonifyURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]


# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"